require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

Style/FrozenStringLiteralComment:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - Rakefile
    - test/test_helper.rb
    - config/boot.rb
    - config/importmap.rb
    - config/application.rb
    - config/initializers/assets.rb
    - config/environments/test.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - app/mailers/application_mailer.rb
Naming/FileName:
  Exclude:
    - config/_PUMA.rb
    - config/_SCHEDULE.rb
    - config/initializers/_CHEWY.rb
    - config/initializers/_CONFIG.rb
    - config/initializers/_REDIS.rb
    - config/initializers/_SIDEKIQ.rb
Style/SymbolArray:
  Exclude:
    - config/initializers/filter_parameter_logging.rb
Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb
Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb
Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - Gemfile
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
Rails/Output:
  Exclude:
    - db/seeds.rb
    - app/jobs/example_job.rb
    - app/models/currency_rate.rb
    - config/environments/development.rb
    - config/initializers/_CHEWY.rb
    - config/initializers/_CONFIG.rb
    - config/initializers/_REDIS.rb
    - config/initializers/_SIDEKIQ.rb
Metrics/MethodLength:
  Exclude:
    - bin/helpers/docker.rb
    - app/controllers/demo_controller.rb
Style/OptionalBooleanParameter:
  Exclude:
    - bin/helpers/docker.rb
Style/OptionalBooleanParameter:
  Exclude:
    - bin/helpers/common.rb
Lint/UselessAssignment:
  Exclude:
    - bin/helpers/puma.rb
    - bin/helpers/sidekiq.rb
Style/GlobalVars:
  Exclude:
    - bin/helpers/common.rb
    - bin/helpers/helpers.rb
    - config/initializers/_REDIS.rb
Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb